version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
      - keycloak
    networks:
      - laminarnet

  frontend:
    image: laminarrun/on-prem-frontend:2024.08.03-v0.0.3
    container_name: frontend
    restart: always
    environment:
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - NEXT_PUBLIC_LAMINAR_API_URL
      - NEXT_PUBLIC_KEYCLOAK_URL
      - NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - NEXT_PUBLIC_ENVIRONMENT=production
      - USE_HTTPS
      - NEXT_PUBLIC_ON_PREM=${ON_PREM}
      - NEXT_PUBLIC_POSTHOG_HOST
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    depends_on:
      api:
        condition: service_healthy
      keycloak:
        condition: service_started

  api:
    image: laminarrun/on-prem-api:2024.08.04-v0.0.5
    container_name: api
    restart: always
    volumes:
      - ./certs:/app/certs:ro
    environment:
      - DB_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_PROFILES_ACTIVE
      - LOGGING_LEVEL_ROOT
      - LOGGING_LEVEL_WEB
      - LOGGING_LEVEL_RUN_LAMINAR
      - LOGTAIL_SOURCE_TOKEN=${NOTIFICATION_API_TOKEN}
      - SPRING_TRANSACTION_DEFAULT_TIMEOUT
      - API_URL
      - SERVER_TOMCAT_ACCEPT_COUNT
      - SERVER_TOMCAT_CONNECTION_TIMEOUT
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
      - NOTIFICATION_API_TOKEN
      - TEMPORAL_SERVICE_ADDRESS
      - KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CLIENT_SECRET
      - KEYCLOAK_URI
      - KEYCLOAK_REALM
      - ON_PREM
      - SERVER_SSL_ENABLED=false
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 180s
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      temporal:
        condition: service_started

  postgres:
    image: postgres:14.12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    environment:
      POSTGRES_USER: laminar
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: laminar
      POSTGRES_MULTIPLE_DATABASES: laminar,keycloak
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "laminar"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=laminar
      - KC_DB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - KC_HOSTNAME=keycloak
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    command:
      - start
      - --import-realm
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  temporal:
    image: temporalio/auto-setup:1.20.0
    container_name: temporal
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=laminar
      - POSTGRES_PWD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_SEEDS=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - laminarnet

  temporal-ui:
    image: temporalio/ui:2.10.3
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=https://localhost
      - TEMPORAL_UI_PORT=8080
      - TEMPORAL_BASE_PATH=/temporal
    depends_on:
      - temporal
    networks:
      - laminarnet

networks:
  laminarnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local