version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
      - keycloak
    networks:
      - laminarnet

  frontend:
    image: laminarrun/on-prem-frontend:2024.08.03-0.0.2
    container_name: frontend
    restart: always
    environment:
      - NEXTAUTH_URL=https://localhost
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_LAMINAR_API_URL=https://localhost/laminar-api
      - NEXT_PUBLIC_KEYCLOAK_URL=https://localhost/auth
      - NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - NEXT_PUBLIC_ENVIRONMENT=production
      - USE_HTTPS=true
      - NEXT_ON_PREM=true
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthcheck"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    depends_on:
      api:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  api:
    image: laminarrun/on-prem-api:2024.08.01-v0.0.1
    container_name: api
    restart: always
    volumes:
      - ./certs:/app/certs:ro
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/laminar
      - SPRING_DATASOURCE_USERNAME=laminar
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT}
      - LOGGING_LEVEL_WEB=${LOGGING_LEVEL_WEB}
      - LOGGING_LEVEL_RUN_LAMINAR=${LOGGING_LEVEL_RUN_LAMINAR}
      - LOGTAIL_SOURCE_TOKEN=${LOGTAIL_SOURCE_TOKEN}
      - SPRING_TRANSACTION_DEFAULT_TIMEOUT=900
      - API_URL=https://localhost/laminar-api
      - SERVER_TOMCAT_ACCEPT_COUNT=300
      - SERVER_TOMCAT_CONNECTION_TIMEOUT=20000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=400
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=2000000
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - NOTIFICATION_API_TOKEN=${NOTIFICATION_API_TOKEN}
      - TEMPORAL_SERVICE_ADDRESS=temporal:7233
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=https://localhost/auth/realms/${KEYCLOAK_REALM}
      - ON_PREM=true
      - SERVER_SSL_ENABLED=false
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 180s
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      temporal:
        condition: service_started

  postgres:
    image: postgres:14.12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=laminar
      - POSTGRES_USER=laminar
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "laminar"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=laminar
      - KC_DB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=443
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_PROXY=edge
    command: start-dev
    networks:
      - laminarnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 30s
    depends_on:
      - postgres

  temporal:
    image: temporalio/auto-setup:1.20.0
    container_name: temporal
    ports:
      - 7233:7233
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=laminar
      - POSTGRES_PWD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres
    networks:
      - laminarnet

  temporal-ui:
    image: temporalio/ui:2.10.3
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=https://localhost
    depends_on:
      - temporal
    networks:
      - laminarnet

networks:
  laminarnet:

volumes:
  postgres_data:
    driver: local