name: Update Docker Compose and Create Release

on:
  repository_dispatch:
    types:
      - version

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Version
        run: echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Update docker-compose.yml
        run: |
          file="docker-compose.yml"
          echo "Updating $file"
          sed -i "s|image: laminarrun/on-prem-frontend:[^ ]*|image: laminarrun/on-prem-frontend:${VERSION}|" "$file"
          sed -i "s|image: laminarrun/on-prem-api:[^ ]*|image: laminarrun/on-prem-api:${VERSION}|" "$file"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "chore(version): bump to ${VERSION}"
          git push origin HEAD

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: ${{ github.event.client_payload.version }}
          draft: false
          prerelease: false
